# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLMNDFBK1wdxlYoBdoqcCFAnY9VBYQdk
"""

import os
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import kagglehub

# ==========================================
# 1. DOWNLOAD DATASET & FIX PATH
# ==========================================
print("1. Downloading dataset from Kaggle...")
path = kagglehub.dataset_download("atharvadarpude/indian-cattle-image-dataset")

# Automatically find the directory containing the breed folders
data_dir = path
for root, dirs, files in os.walk(path):
    # We are looking for the folder that has more than 1 subdirectory (the classes)
    if len(dirs) > 1:
        data_dir = root
        break

print(f"Correct dataset directory located at: {data_dir}")

# ==========================================
# 2. LOAD AND PREPROCESS DATA
# ==========================================
print("\n2. Loading and preprocessing data...")
batch_size = 32
img_size = (224, 224) # Size required by ResNet50

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir, validation_split=0.2, subset="training", seed=123,
    image_size=img_size, batch_size=batch_size, label_mode='categorical'
)
val_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir, validation_split=0.2, subset="validation", seed=123,
    image_size=img_size, batch_size=batch_size, label_mode='categorical'
)

class_names = train_ds.class_names
num_classes = len(class_names)
print(f"\nSUCCESS! Found {num_classes} breeds: {class_names}")

# Apply ResNet50's specific preprocessing to the images
preprocess_input = tf.keras.applications.resnet50.preprocess_input
train_ds = train_ds.map(lambda x, y: (preprocess_input(x), y))
val_ds = val_ds.map(lambda x, y: (preprocess_input(x), y))

# Optimize data pipeline for GPU speed
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# ==========================================
# 3. BUILD TRANSFER LEARNING MODEL
# ==========================================
print("\n3. Building the Transfer Learning Model...")
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.2),
])

# Load base model without top layers, freeze it
base_model = ResNet50(input_shape=(224, 224, 3), include_top=False, weights='imagenet')
base_model.trainable = False
model = tf.keras.models.load_model('indian_cattle_resnet50_finetuned.keras')
# Create new model on top
inputs = tf.keras.Input(shape=(224, 224, 3))
x = data_augmentation(inputs)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x) # Dropout helps prevent overfitting
outputs = layers.Dense(num_classes, activation='softmax')(x)
model = models.Model(inputs, outputs)

# Compile for Phase 1
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='categorical_crossentropy', metrics=['accuracy'])

# ==========================================
# 4. PHASE 1: WARM-UP TRAINING
# ==========================================
print("\n4. Starting Phase 1 (Warm-up Training)...")
early_stopping_1 = EarlyStopping(monitor='val_loss', patience=4, restore_best_weights=True)

history_1 = model.fit(
    train_ds, validation_data=val_ds,
    epochs=15, callbacks=[early_stopping_1]
)

# ==========================================
# 5. PHASE 2: FINE-TUNING
# ==========================================
print("\n5. Starting Phase 2 (Fine-Tuning deep layers)...")
base_model.trainable = True

# Freeze all layers except the last ~30 layers
fine_tune_at = 143
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

# Recompile with a VERY tiny learning rate
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
              loss='categorical_crossentropy', metrics=['accuracy'])

early_stopping_2 = EarlyStopping(monitor='val_loss', patience=4, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=2)

history_2 = model.fit(
    train_ds, validation_data=val_ds,
    epochs=20, callbacks=[early_stopping_2, reduce_lr]
)

# ==========================================
# 6. EVALUATE AND SAVE
# ==========================================
print("\n6. Evaluating Final Model...")
loss, accuracy = model.evaluate(val_ds)
print(f"Final Test Accuracy: {accuracy * 100:.2f}%")

model.save('indian_cattle_resnet50_finetuned.keras')
print("Model saved as 'indian_cattle_resnet50_finetuned.keras'")

# Auto-download the file to your computer
try:
    from google.colab import files
    files.download('indian_cattle_resnet50_finetuned.keras')
except:
    pass